#ifndef ACUTILS_MACROS_H
#define ACUTILS_MACROS_H

#if ACUTILS_ONE_SOURCE
#   define PRIVATE_ACUTILS_ST_FUNC static
#else
#   define PRIVATE_ACUTILS_ST_FUNC
#endif

#define PRIVATE_ACUTILS_ST_DATA PRIVATE_ACUTILS_ST_FUNC

#ifndef ACUTILS_SYMBOL_ATTRIBUTES
#   define ACUTILS_SYMBOL_ATTRIBUTES
#endif

#endif /* ACUTILS_MACROS_H */
