#ifndef APLUGINSDK_SIGNATUREPARSER_H
#define APLUGINSDK_SIGNATUREPARSER_H

#include "macros.h"

PRIVATE_APLUGINSDK_OPEN_PRIVATE_NAMESPACE

    static char** private_APluginSDK_splitParameterList(const char* parameterList);

PRIVATE_APLUGINSDK_CLOSE_PRIVATE_NAMESPACE

#endif /* APLUGINSDK_SIGNATUREPARSER_H */
